language: node_js
node_js:
  - "node"
  - "10"
before_script:
  - "npm run build"
jobs:
  include:
    - stage: test
      script: "npm run lint"
    - stage: test
      script: "npm run mocha"
    - stage: test
      script: "npm run security"
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always